# Generated by Django 6.0.3 on 2026-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='points_left',
            field=models.IntegerField(default=3),
        ),
    ]
