# Generated by Django 6.0.3 on 2026-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coder_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
