# Generated by Django 6.0.3 on 2026-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coder_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
