# Generated by Django 6.0.3 on 2026-03-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coder_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_coders', to='accounts.admin'),
        ),
    ]
