# Generated by Django 6.0.3 on 2026-03-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coder_assigned_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
